title: Build the Résumé of your Future Self
description: In this challenge, you'll begin to understand what it means to be
  a front end developer, and start building the Résumé that you <em>will</em>
  have by the time you complete the program.
published: true
resources:
  1: "http://www.codecademy.com/en/tracks/web"
  2: "http://www.w3schools.com/html/default.asp"
  3: "http://www.w3schools.com/css/default.asp"
  4: "http://adamschwartz.co/magic-of-css/"
  5: "http://www.skilledup.com/articles/life-front-end-web-developer-infographic/"
