title: Sample Challenge
description:
  Do not change or delete this file.  This file will be updated upstream with
  the possible properties that you can use in challenge configuration.

  To get started with the first challenge, create a copy of this file called
  "challenge-config-1-1.yml".
published: false
resources:
  1: "http://www.example.com"
  2: "http://www.google.com"
